=== joelbkoshy/PROJECT/LAB3-XML,XSD,DTD/lab3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Service_centre">

        <xs:complexType>
            <xs:sequence>
                <xs:element name="Services" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SERVICE_ID">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="100"/>
                                        <xs:maxInclusive value="999"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="SERVICE_TYPE">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="INTERIM SERVICE"/>
                                        <xs:enumeration value="FULL SERVICE"/>
                                        <xs:enumeration value="MAJOR SERVICE"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="SERVICE_CHARGE">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="150"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="VEHICLE_TYPE">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="CAR"/>
                                        <xs:enumeration value="BIKE"/>
                                        <xs:enumeration value="TRUCK"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>



            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== joelbkoshy/PROJECT/LAB3-XML,XSD,DTD/lab3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="lab3.xsl" type="text/xsl"?>
<!-- <!DOCTYPE Service_centre SYSTEM "sevice.dtd"> -->
<Service_centre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lab3.xsd">
  <Services>
    <SERVICE_ID>100</SERVICE_ID>
    <SERVICE_TYPE>INTERIM SERVICE</SERVICE_TYPE>
    <SERVICE_CHARGE>450</SERVICE_CHARGE>
    <VEHICLE_TYPE>CAR</VEHICLE_TYPE>
  </Services>

  <Services>
    <SERVICE_ID>102</SERVICE_ID>
    <SERVICE_TYPE>FULL SERVICE</SERVICE_TYPE>
    <SERVICE_CHARGE>5450</SERVICE_CHARGE>
    <VEHICLE_TYPE>TRUCK</VEHICLE_TYPE>
  </Services>

  <Services>
    <SERVICE_ID>104</SERVICE_ID>
    <SERVICE_TYPE>MAJOR SERVICE</SERVICE_TYPE>
    <SERVICE_CHARGE>4650</SERVICE_CHARGE>
    <VEHICLE_TYPE>BIKE</VEHICLE_TYPE>
  </Services>

  <Services>
    <SERVICE_ID>101</SERVICE_ID>
    <SERVICE_TYPE>FULL SERVICE</SERVICE_TYPE>
    <SERVICE_CHARGE>6550</SERVICE_CHARGE>
    <VEHICLE_TYPE>TRUCK</VEHICLE_TYPE>
  </Services>

  <Services>
    <SERVICE_ID>103</SERVICE_ID>
    <SERVICE_TYPE>INTERIM SERVICE</SERVICE_TYPE>
    <SERVICE_CHARGE>850</SERVICE_CHARGE>
    <VEHICLE_TYPE>BIKE</VEHICLE_TYPE>
  </Services>


</Service_centre>
